### ISSUE TITLE
VAProfileVVCMain10

### ISSUE THREAD

**Issue by Kender0221** [intel/vpl-gpu-rt#367]
make vpl-gpu-rt时出现VAProfileVVCMain10的报错，libva和media-driver已经是最新的版本，支持VVC
大概是什么问题？库链接嘛？

**Comment by smitdylan2001** [comment]
I also get ‘VAProfileVVCMain10’ was not declared in this scope; did you mean ‘VAProfileHEVCMain10’?

**Comment by samvv** [comment]
Same problem here, Ubuntu 24.04. Did anyone solve this?

**Comment by jinyuan-dev** [comment]
VVC decode is only supported on LNL+ platforms and not supported on Arc A380. So run vainfo on Arc A380 will not get ‘VAProfileVVCMain10’.

Refer to https://github.com/intel/media-driver#decodingencoding-features for supported codecs' features on different platforms.

**Comment by jinyuan-dev** [comment]
> make vpl-gpu-rt时出现VAProfileVVCMain10的报错，libva和media-driver已经是最新的版本，支持VVC 大概是什么问题？库链接嘛？

My local build on Ubuntu 24.04 didn't meet this issue (undefined VAProfileVVCMain10). What I did:

1. Build and install the latest libva
    following the instructions in: https://github.com/intel/libva
    (1) sudo apt-get install git cmake pkg-config meson libdrm-dev automake libtool
    (2) git clone https://github.com/intel/libva.git
         cd libva
    (3) Build libva with autogen:
         ./autogen.sh --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu
         make
         sudo make install
2. Build and install the latest media-driver
    I installed version 26.2.1-17602 for intel-media Open Source Driver
3. Follow https://github.com/intel/vpl-gpu-rt#build-steps: 
    (1) git clone https://github.com/intel/vpl-gpu-rt vpl-gpu-rt
         cd vpl-gpu-rt
    (2) mkdir build && cd build
         cmake ..
         make
         make install

Note: VAProfileVVCMain10 is defined from libva version 2.22.0: https://github.com/intel/libva/releases/tag/2.22.0

**Comment by teasit** [comment]
> > make vpl-gpu-rt时出现VAProfileVVCMain10的报错，libva和media-driver已经是最新的版本，支持VVC 大概是什么问题？库链接嘛？
> 
> My local build on Ubuntu 24.04 didn't meet this issue (undefined VAProfileVVCMain10). What I did:
> 
> 1. Build and install the latest libva
>    following the instructions in: https://github.com/intel/libva
>    (1) sudo apt-get install git cmake pkg-config meson libdrm-dev automake libtool
>    (2) git clone https://github.com/intel/libva.git
>    cd libva
>    (3) Build libva with autogen:
>    ./autogen.sh --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu
>    make
>    sudo make install
> 2. Build and install the latest media-driver
>    I installed version 26.2.1-17602 for intel-media Open Source Driver
> 3. Follow https://github.com/intel/vpl-gpu-rt#build-steps:
>    (1) git clone https://github.com/intel/vpl-gpu-rt vpl-gpu-rt
>    cd vpl-gpu-rt
>    (2) mkdir build && cd build
>    cmake ..
>    make
>    make install
> 
> Note: VAProfileVVCMain10 is defined from libva version 2.22.0: https://github.com/intel/libva/releases/tag/2.22.0

Installing libva as you outlined also solved the mentioned issue.
